apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  labels:
    app: api-gateway
    component: config
data:
  NODE_ENV: "production"
  PORT: "8601"
  
  # Service URLs
  USER_SERVICE_URL: "http://user-service:8602"
  OCR_SERVICE_URL: "http://ocr-service:8603"
  OCR_ENGINE_SERVICE_URL: "http://ocr-engine-service:8604"
  PATIENT_QUEUE_SERVICE_URL: "http://patient-queue-service:8605"
  
  # RabbitMQ Configuration
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_VHOST: "mediq"
  RABBITMQ_EXCHANGE: "mediq_exchange"
  
  # Circuit Breaker Configuration
  CIRCUIT_BREAKER_TIMEOUT: "5000"
  CIRCUIT_BREAKER_ERROR_THRESHOLD: "5"
  CIRCUIT_BREAKER_RESET_TIMEOUT: "30000"
  
  # Rate Limiting
  RATE_LIMIT_WINDOW: "900000"
  RATE_LIMIT_MAX_REQUESTS: "1000"
  
  # Retry Configuration
  MAX_RETRIES: "3"
  RETRY_DELAY: "1000"
  
  # Health Check
  HEALTH_CHECK_INTERVAL: "30000"
  HEALTH_CHECK_TIMEOUT: "5000"
  
  # Swagger Configuration
  SWAGGER_ENABLED: "true"
  SWAGGER_PATH: "/api/docs"

  # Public API Key for external access (set secret via Secret in prod)
  PUBLIC_API_KEY: ""
  
  # CORS Configuration
  CORS_ENABLED: "true"
  CORS_ORIGINS: "*"
  
  # Logging
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
